### ISSUE TITLE
Can't create directory in XCode Template

### ISSUE THREAD

**Issue by dorianmariecom** [joemasilotti/TurboNativeXcodeTemplate#3]
```
~/s/god> echo $DIR
/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/Custom Templates
~/s/god> mkdir -p $DIR
mkdir: /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates: Operation not permitted
~/s/god> sudo mkdir -p $DIR
mkdir: /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates: Operation not permitted
~/s/god> ll /Applications/Xcode.app/Contents/Developer/Library/Xcode/
total 0
drwxr-xr-x  4 root  wheel   128B Jul  6 19:02 ./
drwxr-xr-x  7 root  wheel   224B May 20 03:16 ../
drwxr-xr-x  4 root  wheel   128B May 20 03:26 Agents/
drwxr-xr-x  3 root  wheel    96B May 20 01:16 Plug-ins/
```

**Comment by joemasilotti** [comment]
I think you need to grant "Full Disk Access" to your terminal of choice. The files under `/Applications/` seem to be a bit protected.

https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

Does that help?

**Comment by dorianmariecom** [comment]
I also needed to sudo

```
~/s/god> mkdir -p $DIR
mkdir: /Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates: Permission denied
~/s/god> sudo mkdir -p $DIR
Password:
~/s/god> 
```

Thanks, for some reason I thought I needed to give XCode full disk access

**Comment by dorianmariecom** [comment]
I also needed to sudo for the cloning

```
~/s/god> git clone git@github.com:joemasilotti/TurboNativeXcodeTemplate.git $DIR/Turbo\ Native\ App.xctemplate
fatal: could not create work tree dir '/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/Custom Templates/Turbo Native App.xctemplate': Permission denied
~/s/god> sudo git clone git@github.com:joemasilotti/TurboNativeXcodeTemplate.git $DIR/Turbo\ Native\ App.xctemplate
Cloning into '/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/Custom Templates/Turbo Native App.xctemplate'...
```

**Comment by dorianmariecom** [comment]
Now in XCode I get

<img width="245" alt="Screenshot 2023-07-06 at 19 19 26" src="https://github.com/joemasilotti/TurboNativeXcodeTemplate/assets/58794487/a73a850a-0bf2-4912-a88f-f80763533a60">

**Comment by dorianmariecom** [comment]
Showing Recent Issues
Build service could not create build operation: unable to load transferred PIF: Required key 'productTypeIdentifier' is missing in StandardTarget dictionary

**Comment by joemasilotti** [comment]
Can you try instead cloning into `~/Library/Developer/Xcode/Templates/Project Templates/`?

**Comment by joemasilotti** [comment]
I just updated the README to use the new directory. I think that should fix your issue!

Make sure to add the `turbo-ios` Swift package after creating the project.

**Comment by dorianmariecom** [comment]
```
~/s/god> git clone git@github.com:joemasilotti/TurboNativeXcodeTemplate.git $DIR/Turbo\ Native\ App.xctemplate
Cloning into '~/Library/Developer/Xcode/Templates/Custom Templates/Turbo Native App.xctemplate'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 28 (delta 4), reused 8 (delta 2), pack-reused 16
Receiving objects: 100% (28/28), 22.80 MiB | 3.09 MiB/s, done.
Resolving deltas: 100% (4/4), done.
```

<img width="812" alt="Screenshot 2023-07-06 at 19 32 41" src="https://github.com/joemasilotti/TurboNativeXcodeTemplate/assets/58794487/d0d240ea-f8ee-4b02-a2f5-431dc11f218c">

The template doesn't appear

**Comment by joemasilotti** [comment]
Weird. Can you try quitting and reopening Xcode?

**Comment by dorianmariecom** [comment]
```
~/s/god> mkdir -p ~/Library/Developer/Xcode/Templates/Custom\ Templates
~/s/god> git clone git@github.com:joemasilotti/TurboNativeXcodeTemplate.git ~/Library/Developer/Xcode/Templates/Custom\ Templates/Turbo\ Native\ App.xctemplate
```

**Comment by dorianmariecom** [comment]
`~` in variables doesn't get interpreted I think

**Comment by dorianmariecom** [comment]
yeah now I find the template

**Comment by joemasilotti** [comment]
> `~` in variables doesn't get interpreted I think

Maybe that is fish shell? It seems to work fine on zsh.

But glad to hear that it is working for you! I'm going to close this out.
